"use client";

import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";
import React, { FC, ReactNode } from "react";
import { DivWrapperSC } from "./styles.page";


const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<{ children: ReactNode }> = (props) => {
    const { children } = props;

    return (
        <html lang="en">
            <head>
                <link rel="icon" href="favicon.svg" sizes="any" />
            </head>
            <title>Todo-app</title>
            <body id="root">
                <StyledComponentsRegistry>
                    <DivWrapperSC>
                        {children}
                    </DivWrapperSC>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
};

export default RootLayout;
